[tool.poetry]
name = "familytree"
version = "0.1.0"
description = ""
authors = ["Ali Elnwegy"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.11"
toga = "^0.4.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
